config/routes.rb
Kixo::Application.routes.draw do
  # I18n
  scope "(:locale)", :locale => /fr|en/ do
    devise_for :users, :controllers => {:registrations => "users/registrations", :sessions => "users/sessions"}

    devise_scope :user do
      get "/users/sign_up/professional" => "users/registrations#new_professional", :as => :new_professional_registration
      post "/users/sign_up/professional" => "users/registrations#create_professional", :as => :create_professional_registration
      get "/users/crop_headshot" => "users/registrations#crop_headshot", :as => :crop_user_headshot
      get "/users/change_plan/:plan" => "users/registrations#change_plan", :as => :change_user_plan
      resources :cards
    end

    resources :professionals do
      collection do
        get "search"
      end
    end

    resources :conversations do
      resources :messages
    end

    resources :notifications

    resources :questions do
      collection do
        get "mine"
        get "for_me"
        get "most_popular"
        get "answered"
        get "unanswered"
      end

      resources :answers
    end

    resources :categories do
      resources :topics
      resources :professions
    end

    resources :countries do
      resources :regions do
        resources :localities
      end
    end

    resources :localities do
      resources :topics
      resources :professions
    end

    resources :pages, :only => [:show]

    resources :guides

    resources :comments

    namespace :data do
      resources :whats
      resources :wheres
      resources :localities
    end

    namespace :admin do
      resources :users
      resources :questions
      resources :pages
      resources :professions
      resources :topics
      resources :taxonomies do
        resources :names
        resources :descriptions
      end
      resources :ads

      root :to => "dashboard#index"
    end
  end

  match "/:locale" => "questions#index"

  root :to => "questions#index"
end

app/models/taxonomies/locality.rb
class Locality < Taxonomy
  attr_accessible :region

  # a locality (a.k.a. city) belongs to a region (which belongs to a country in turn)
  belongs_to :region, :foreign_key => :parent_id

  has_many :users, :foreign_key => :locality_id
  has_many :professionals, :class_name => "User", :foreign_key => :locality_id, :conditions => {:is_professional => true}

  geocoded_by :geocoding_address
  after_validation :geocode

  def population
    self.rank
  end

  def geocoding_address
    "#{self.name}, #{self.region.name}, #{self.region.country.name}"
  end

  def self.sort_by_population
    self.sort_by(&:population)
  end

  def self.order_by_population
    self.order_by_rank
  end

  def self.most_populated(n = 10)
    self.order_by_population.limit(n)
  end

  def self.most_popular(n = 10)
    self.order("questions_count DESC, users_count DESC, rank DESC").limit(n)
  end
end

app/controllers/data/localities_controller.rb
class Data::LocalitiesController < ApplicationController
  def index
    if params[:region_id]
      @region = Region.find(params[:region_id])
      @country = @region.country
      @localities = @region.localities
    elsif params[:country_id]
      @country = Country.find(params[:country_id])
      @localities = @country.localities
    else
      if params[:term]
        @localities = Locality.search(params[:term])
      else
        @localities = Locality.all
      end
    end

    @humanized_localities = @localities.sort_by(&:rank).reverse.map(&:name)

    respond_to do |format|
      format.json { render :json => @humanized_localities }
      format.xml  { render :xml => @humanized_localities }
    end
  end
end

app/controllers/localities_controller.rb
class LocalitiesController < ApplicationController

  def index
    if params[:region_id]
      @region = Region.find(params[:region_id])
      @country = @region.country
      @localities = @region.localities
    elsif params[:country_id]
      @country = Country.find(params[:country_id])
      @localities = @country.localities
    else
      @localities = Locality.all
    end

    respond_to do |format|
      format.html
      format.json { render :json => @localities }
      format.xml  { render :xml => @localities }
    end
  end

  def show
    @locality = Locality.find(params[:id])
    @region = @locality.region
    @country = @region.country

    @where = @locality.name

    @professionals = @locality.professionals

    respond_to do |format|
      format.html
      format.json { render :json => @locality }
      format.xml  { render :xml => @locality }
    end
  end

end

app/helpers/data/localities_helper.rb
module Data::LocalitiesHelper
end

app/helpers/localities_helper.rb
module LocalitiesHelper
end

app/views/localities/show.html.haml
- content_for :title, t("localities.show.page_title", :locality => @locality.name, :region => @region.name)

= render "shared/hero", :slim => true, :who => @who, :where => @where
%section#content
  .container
    .row
      .twelve.columns
        %h1= @locality.name
        %hr
      .nine.columns
        %section.browse-by-taxonomy
          .container
            %ul.categories.accordion.compact
              - @all_categories.each do |category|
                %li.category
                  .title
                    %h5.category-name
                      = category.name
                  .content
                    %ul
                      %li
                        %h5.topics-title
                          = t("topics.index.title")
                        %ul.topics.block-grid.three-up
                          - category.topics.each do |topic|
                            %li.topic
                              = link_to topic.name, locality_topic_path(@locality, topic), :class => "topic-name", :title => "#{topic.name} - #{@locality.name}, #{@region.name}"
                      %li
                        %h5.professions-title
                          = t("professions.index.title")
                        %ul.professions.block-grid.three-up
                          - category.professions.each do |profession|
                            %li.profession
                              = link_to profession.name, locality_profession_path(@locality, profession), :class => "profession-name", :title => "#{profession.name} - #{@locality.name}, #{@region.name}"
      .three.columns
        %section
          %h5.section-title= t("professionals.top_rated.in_locality.title", :locality => @locality.name).html_safe
          - unless @professionals.empty?
            %ul.looper.professionals.top-rated-professionals
              - @professionals.each do |professional|
                %li= render "professionals/loops/minimal", :professional => professional
          - else
            %p.no-records
              = t("professionals.count.zero").html_safe