config/routes.rb
Kixo::Application.routes.draw do
  # I18n
  scope "(:locale)", :locale => /fr|en/ do
    devise_for :users, :controllers => {:registrations => "users/registrations", :sessions => "users/sessions"}

    devise_scope :user do
      get "/users/sign_up/professional" => "users/registrations#new_professional", :as => :new_professional_registration
      post "/users/sign_up/professional" => "users/registrations#create_professional", :as => :create_professional_registration
      get "/users/crop_headshot" => "users/registrations#crop_headshot", :as => :crop_user_headshot
      get "/users/change_plan/:plan" => "users/registrations#change_plan", :as => :change_user_plan
      resources :cards
    end

    resources :professionals do
      collection do
        get "search"
      end
    end

    resources :conversations do
      resources :messages
    end

    resources :notifications

    resources :questions do
      collection do
        get "mine"
        get "for_me"
        get "most_popular"
        get "answered"
        get "unanswered"
      end

      resources :answers
    end

    resources :categories do
      resources :topics
      resources :professions
    end

    resources :countries do
      resources :regions do
        resources :localities
      end
    end

    resources :localities do
      resources :topics
      resources :professions
    end

    resources :pages, :only => [:show]

    resources :guides

    resources :comments

    namespace :data do
      resources :whats
      resources :wheres
      resources :localities
    end

    namespace :admin do
      resources :users
      resources :questions
      resources :pages
      resources :professions
      resources :topics
      resources :taxonomies do
        resources :names
        resources :descriptions
      end
      resources :ads

      root :to => "dashboard#index"
    end
  end

  match "/:locale" => "questions#index"

  root :to => "questions#index"
end

app/models/conversation.rb
class Conversation < ActiveRecord::Base
  acts_as_paranoid

  attr_accessible :participants, :participant_ids, :deleted_at

  has_many :conversation_participations
  has_many :participants, :through => :conversation_participations, :class_name => "User"

  has_many :messages, :dependent => :destroy, :order => "created_at ASC"

  accepts_nested_attributes_for :messages
  attr_accessible :messages_attributes

  def other_participants(user)
    self.participants.where("users.id != ?", user.id)
  end
end

app/controllers/conversations_controller.rb
class ConversationsController < ApplicationController
  before_filter :authenticate_user!
  before_filter :verify_if_participant!, :only => [:show, :edit, :update, :destroy, :reply]

  def index
    @conversations = current_user.conversations.page(params[:page])

    # pagination
    if @conversations.kind_of?(Array)
      Kaminari.paginate_array(@conversations).page(params[:page])
    else
      @conversations.page(params[:page])
    end

    respond_to do |format|
      format.html
      format.json { render :json => @conversations }
      format.xml  { render :xml  => @conversations }
    end
  end

  def show
    @conversation = Conversation.find(params[:id])
    @messages = @conversation.messages.all

    @reply = @conversation.messages.build

    track_event "View Conversation"

    respond_to do |format|
      format.html
      format.json { render :json => @conversation }
      format.xml  { render :xml => @conversation }
    end
  end

  def new
    @conversation = Conversation.new(params[:conversation])
    @conversation.messages.build
  end

  def create
    params[:conversation][:participant_ids] = params[:conversation][:participant_ids].split(",").collect{|id| id.to_i}
    @conversation = Conversation.new(params[:conversation])

    @conversation.participants << current_user

    @conversation.messages.each do |message|
      message.author = current_user
    end

    respond_to do |format|
      if @conversation.save
        format.html { redirect_to @conversation }
        format.json { render :json => @conversation, :status => :created, :location => @conversation }
        format.xml  { render :xml => @conversation, :status => :created, :location => @conversation }
      else
        format.html { render :action => "new" }
        format.json { render :json => @conversation.errors, :status => :unprocessable_entity }
        format.xml  { render :xml => @conversation.errors, :status => :unprocessable_entity }
      end
    end
  end

  private

  def verify_if_participant!
    conversation = Conversation.find(params[:id])
    unless conversation.participants.include?(current_user)
      flash[:error] = t("security.access_denied")
      redirect_to root_path
    end
  end

end

app/helpers/conversations_helper.rb
module ConversationsHelper
end

app/views/conversations/index.html.haml
%section#content
  .container
    .row
      .two.columns
        %ul.side-nav
          %li.active= link_to t("conversations.inbox.label"), conversations_path
          =#%li.divider
          =#%li= link_to t("messages.new.label"), new_conversation_path
      .ten.columns
        .page
          %header
            .container
              %h1
                = t("messages.index.title")
          %section
            .container
              - unless @conversations.blank?
                .conversations
                  - @conversations.each do |conversation|
                    = render "conversations/shared/loop", :conversation => conversation
              - else
                %p.no-records
                  = t("conversations.inbox.empty")

app/views/conversations/new.html.haml
%section#content
  .container
    .row
      .two.columns
        %ul.side-nav
          %li= link_to t("conversations.inbox.label"), conversations_path
          =#%li.divider
          =#%li.active= link_to t("messages.new.label"), new_conversation_path
      .ten.columns
        = simple_form_for @conversation do |f|
          .page
            %header
              .container
                %hgroup
                  %h1= t("messages.new.title")
                  %h4.subheader= t("messages.new.subtitle")
            = render "shared/errors", object: f.object
            %section
              .container
                = f.input :participant_ids, :as => :hidden, :id => "new_conversation_participant_id"
                = f.simple_fields_for :messages, @conversation.messages do |m|
                  = m.input :message, :as => :text, :required => false, :label => false
            %section.actions
              .container
                = f.button :submit, t("messages.new.submit")

app/views/conversations/show.html.haml
%section#content
  .container
    .row
      .two.columns
        %ul.side-nav
          %li= link_to t("conversations.inbox.label"), conversations_path
          =#%li.divider
          =#%li= link_to t("messages.new.label"), new_conversation_path
      .ten.columns
        .page
          %header
            .container
              .row
                .six.columns
                  %hgroup
                    %h1= t("conversations.show.title")
                    %h4.subheader= t("conversations.show.subtitle", :other_participants => @conversation.other_participants(current_user).map(&:name).join(", "))
                .six.columns.text-right
                  - @conversation.other_participants(current_user).each do |participant|
                    - if participant.is_professional?
                      = link_to professional_path(participant) do
                        = image_tag participant.headshot.url(:mini), :class => "headshot"
                    - else
                      = image_tag participant.headshot.url(:mini), :class => "headshot"
          %section
            .container
              - @messages.each do |message|
                = render "messages/shared/loop", :message => message
          %section.reply
            .container
              .row
                .two.columns.text-center
                  = image_tag current_user.headshot.url(:small), :class => "headshot"
                .ten.columns
                  %h4= t("messages.reply.title")
                  = simple_form_for [@conversation, @reply] do |f|
                    = f.input :message, :as => :text, :input_html => {:rows => 10}, :label => false
                    = f.button :submit, t("messages.reply.submit")