config/routes.rb
Kixo::Application.routes.draw do
  # I18n
  scope "(:locale)", :locale => /fr|en/ do
    devise_for :users, :controllers => {:registrations => "users/registrations", :sessions => "users/sessions"}

    devise_scope :user do
      get "/users/sign_up/professional" => "users/registrations#new_professional", :as => :new_professional_registration
      post "/users/sign_up/professional" => "users/registrations#create_professional", :as => :create_professional_registration
      get "/users/crop_headshot" => "users/registrations#crop_headshot", :as => :crop_user_headshot
      get "/users/change_plan/:plan" => "users/registrations#change_plan", :as => :change_user_plan
      resources :cards
    end

    resources :professionals do
      collection do
        get "search"
      end
    end

    resources :conversations do
      resources :messages
    end

    resources :notifications

    resources :questions do
      collection do
        get "mine"
        get "for_me"
        get "most_popular"
        get "answered"
        get "unanswered"
      end

      resources :answers
    end

    resources :categories do
      resources :topics
      resources :professions
    end

    resources :countries do
      resources :regions do
        resources :localities
      end
    end

    resources :localities do
      resources :topics
      resources :professions
    end

    resources :pages, :only => [:show]

    resources :guides

    resources :comments

    namespace :data do
      resources :whats
      resources :wheres
      resources :localities
    end

    namespace :admin do
      resources :users
      resources :questions
      resources :pages
      resources :professions
      resources :topics
      resources :taxonomies do
        resources :names
        resources :descriptions
      end
      resources :ads

      root :to => "dashboard#index"
    end
  end

  match "/:locale" => "questions#index"

  root :to => "questions#index"
end

app/models/taxonomies/topic.rb
class Topic < Taxonomy
  attr_accessible :category

  # a topic belongs in a category
  belongs_to :category, :foreign_key => "parent_id"

  has_many :classifications, :as => :taxonomy, :foreign_key => :taxonomy_id, :source_type => "Topic"
  has_many :professionals, :through => :classifications, :source => :classifiable, :source_type => "User", :conditions => {:is_professional => true}
  has_many :questions,     :through => :classifications, :source => :classifiable, :source_type => "Question"
  has_many :guides,        :through => :classifications, :source => :classifiable, :source_type => "Guide"

  def self.most_popular(n = 10)
    self.order("questions_count DESC, users_count DESC").limit(n)
  end
end

app/controllers/admin/topics_controller.rb
class Admin::TopicsController < ApplicationController
  before_filter :authenticate_admin

  def index
    @topics = Topic.order("id ASC")
  end

  def new
    @topic = Topic.new(params[:topic])
  end

  def create
    @topic = Topic.new(params[:topic])

    respond_to do |format|
      if @topic.save
        format.html do
          flash[:success] = t("admin.topic.create.success")
          redirect_to edit_admin_profession_path(@topic)
        end
        format.json { render :json => @topic, :status => :created, :location => @topic }
        format.xml  { render :xml => @topic, :status => :created, :location => @topic }
      else
        format.html { render :action => "new" }
        format.json { render :json => @topic.errors, :status => :unprocessable_entity }
        format.xml  { render :xml => @topic.errors, :status => :unprocessable_entity }
      end
    end
  end

  def edit
    @topic = Topic.find(params[:id])
  end

  def update
    @topic = Topic.find(params[:id])

    respond_to do |format|
      if @topic.update_attributes(params[:topic])
        format.html do
          flash[:success] = t("admin.topic.update.success")
          redirect_to edit_admin_profession_path(@topic)
        end
        format.json { head :no_content }
        format.xml  { head :no_content }
      else
        format.html do
          flash[:error] = t("admin.topic.update.error")
          render action: "edit"
        end
        format.json { render :json => @topic.errors, :status => :unprocessable_entity }
        format.xml  { render :xml => @topic.errors, :status => :unprocessable_entity }
      end
    end
  end

  def destroy
    @topic = Topic.find(params[:id])

    respond_to do |format|
      format.html do
        if @topic.destroy
          flash[:success] = t("admin.topic.destroy.success")
          redirect_to admin_professions_path
        else
          flash[:error] = t("admin.topic.destroy.error")
          redirect_to edit_admin_profession_path(@topic)
        end
      end
      format.json { head :no_content }
      format.xml  { head :no_content }
    end
  end
end

app/controllers/topics_controller.rb
class TopicsController < ApplicationController

  def index
    @category = Category.find(params[:category_id]) unless params[:category_id].nil?
    @topics = @category ? @category.topics : Topic.all

    @humanized_topics = @topics.map {|topic| {:id => topic.id, :name => topic.name}}

    respond_to do |format|
      format.html
      format.json { render :json => @humanized_topics }
      format.xml  { render :xml => @humanized_topics }
    end
  end

  def show
    @topic = Topic.find(params[:id])

    @questions = @topic.questions.find_all_by_locale(@user_locale)
    @professionals = @topic.professionals

    unless params[:locality_id].nil?
      @locality = Locality.find(params[:locality_id])
      @professionals = @professionals.merge(@locality.professionals) unless @locality.nil?
    end

    respond_to do |format|
      format.html
      format.json { render :json => @topic }
      format.xml  { render :xml => @topic }
    end
  end

end

app/helpers/topics_helper.rb
module TopicsHelper
end

app/views/admin/topics/edit.html.haml
%section#content
  .container
    .row
      .two.columns
        = render "admin/shared/nav"
      .ten.columns
        = simple_form_for [:admin, @topic] do |f|
          .page.admin
            %header
              .container
                .row
                  .six.columns
                    %h1 Edit Topic
                  .six.columns.text-right
                    = link_to "All Topics", admin_topics_path, :class => "button secondary"
            = render "shared/errors", object: f.object
            %section
              %header
                .container
                  %h3 Names
              .container
                .duplicatable-nested-fields
                  = f.simple_fields_for :names do |name_form|
                    .nested-fields
                      .row
                        .ten.columns
                          = name_form.input :name
                        .two.columns
                          = name_form.association :locale
                      - if name_form.object.new_record?
                        = link_to 'Remove', '', :remote => true, :class => 'destroy-nested-fields'
                      - else
                        = link_to 'Remove', admin_taxonomy_name_path(@topic, name_form.object), :method => :delete, :remote => true, :class => 'destroy-nested-fields'
                        = name_form.input :id, :as => :hidden
                  - if @topic.names.empty?
                    = f.simple_fields_for :names, @topic.names.build do |name_form|
                      .nested-fields
                        .row
                          .ten.columns
                            = name_form.input :name
                          .two.columns
                            = name_form.association :locale
                        - if name_form.object.new_record?
                          = link_to 'Remove', '', :remote => true, :class => 'destroy-nested-fields'
                        - else
                          = link_to 'Remove', admin_taxonomy_name_path(@topic, name_form.object), :method => :delete, :remote => true, :class => 'destroy-nested-fields'
                          = name_form.input :id, :as => :hidden
                  = link_to 'Add Another Name', '', :class => 'duplicate-nested-fields'
            %section
              %header
                .container
                  %h3 Descriptions
              .container
                .duplicatable-nested-fields
                  = f.simple_fields_for :descriptions do |description_form|
                    .nested-fields
                      .row
                        .ten.columns
                          = description_form.input :description, :as => :text, :input_html => {:rows => 5}
                        .two.columns
                          = description_form.association :locale
                      - if description_form.object.new_record?
                        = link_to 'Remove', '', :remote => true, :class => 'destroy-nested-fields'
                      - else
                        = link_to 'Remove', admin_taxonomy_description_path(@topic, description_form.object), :method => :delete, :remote => true, :class => 'destroy-nested-fields'
                        = description_form.input :id, :as => :hidden
                  - if @topic.descriptions.empty?
                    = f.simple_fields_for :descriptions, @topic.descriptions.build do |description_form|
                      .nested-fields
                        .row
                          .ten.columns
                            = description_form.input :description, :as => :text, :input_html => {:rows => 5}
                          .two.columns
                            = description_form.association :locale
                        - if description_form.object.new_record?
                          = link_to 'Remove', '', :remote => true, :class => 'destroy-nested-fields'
                        - else
                          = link_to 'Remove', admin_taxonomy_description_path(@topic, description_form.object), :method => :delete, :remote => true, :class => 'destroy-nested-fields'
                          = description_form.input :id, :as => :hidden
                  = link_to 'Add Another Description', '', :class => 'duplicate-nested-fields'
            %section
              .container
                = f.association :parent
            %section.actions
              .container
                = f.button :submit

app/views/admin/topics/index.html.haml
%section#content
  .container
    .row
      .two.columns
        = render "admin/shared/nav"
      .ten.columns
        .page.admin.taxonomies
          %header
            .container
              .row
                .six.columns
                  %h1 Topics
                .six.columns.text-right
                  = link_to "New Topic", new_admin_topic_path, :class => "button"
          %section
            %table.admin-table
              %thead
                %tr
                  %th Name
                  %th Parent
                  %th Actions
              %tbody
                - @topics.each do |topic|
                  %tr
                    %td.name
                      = topic.name
                    %td.parent
                      = topic.parent.name if topic.parent
                    %td.actions
                      = link_to "Edit", edit_admin_topic_path(topic), :class => "button tiny"
                      = link_to "Delete", admin_topic_path(topic), :method => :delete, :class => "button tiny alert"

app/views/admin/topics/new.html.haml
%section#content
  .container
    .row
      .two.columns
        = render "admin/shared/nav"
      .ten.columns
        = simple_form_for [:admin, @topic] do |f|
          .page.admin
            %header
              .container
                .row
                  .six.columns
                    %h1 New Topic
                  .six.columns.text-right
                    = link_to "All Topics", admin_topics_path, :class => "button secondary"
            = render "shared/errors", object: f.object
            %section
              %header
                .container
                  %h3 Names
              .container
                .duplicatable-nested-fields
                  = f.simple_fields_for :names, @topic.names.build do |name_form|
                    .nested-fields
                      .row
                        .ten.columns
                          = name_form.input :name
                        .two.columns
                          = name_form.association :locale
                      - if name_form.object.new_record?
                        = link_to 'Remove', '', :remote => true, :class => 'destroy-nested-fields'
                      - else
                        = link_to 'Remove', admin_taxonomy_name_path(@topic, name_form.object), :method => :delete, :remote => true, :class => 'destroy-nested-fields'
                        = name_form.input :id, :as => :hidden
                  = link_to 'Add Another Name', '', :class => 'duplicate-nested-fields'
            %section
              %header
                .container
                  %h3 Descriptions
              .container
                .duplicatable-nested-fields
                  = f.simple_fields_for :descriptions, @topic.descriptions.build do |description_form|
                    .nested-fields
                      .row
                        .ten.columns
                          = description_form.input :description, :as => :text, :input_html => {:rows => 5}
                        .two.columns
                          = description_form.association :locale
                      - if description_form.object.new_record?
                        = link_to 'Remove', '', :remote => true, :class => 'destroy-nested-fields'
                      - else
                        = link_to 'Remove', admin_taxonomy_description_path(@topic, description_form.object), :method => :delete, :remote => true, :class => 'destroy-nested-fields'
                        = description_form.input :id, :as => :hidden
                  = link_to 'Add Another Description', '', :class => 'duplicate-nested-fields'
            %section
              .container
                = f.association :parent
            %section.actions
              .container
                = f.button :submit