config/routes.rb
Kixo::Application.routes.draw do
  # I18n
  scope "(:locale)", :locale => /fr|en/ do
    devise_for :users, :controllers => {:registrations => "users/registrations", :sessions => "users/sessions"}

    devise_scope :user do
      get "/users/sign_up/professional" => "users/registrations#new_professional", :as => :new_professional_registration
      post "/users/sign_up/professional" => "users/registrations#create_professional", :as => :create_professional_registration
      get "/users/crop_headshot" => "users/registrations#crop_headshot", :as => :crop_user_headshot
      get "/users/change_plan/:plan" => "users/registrations#change_plan", :as => :change_user_plan
      resources :cards
    end

    resources :professionals do
      collection do
        get "search"
      end
    end

    resources :conversations do
      resources :messages
    end

    resources :notifications

    resources :questions do
      collection do
        get "mine"
        get "for_me"
        get "most_popular"
        get "answered"
        get "unanswered"
      end

      resources :answers
    end

    resources :categories do
      resources :topics
      resources :professions
    end

    resources :countries do
      resources :regions do
        resources :localities
      end
    end

    resources :localities do
      resources :topics
      resources :professions
    end

    resources :pages, :only => [:show]

    resources :guides

    resources :comments

    namespace :data do
      resources :whats
      resources :wheres
      resources :localities
    end

    namespace :admin do
      resources :users
      resources :questions
      resources :pages
      resources :professions
      resources :topics
      resources :taxonomies do
        resources :names
        resources :descriptions
      end
      resources :ads

      root :to => "dashboard#index"
    end
  end

  match "/:locale" => "questions#index"

  root :to => "questions#index"
end

app/models/taxonomies/category.rb
class Category < Taxonomy
  has_many :topics,      :foreign_key => "parent_id"
  has_many :professions, :foreign_key => "parent_id"

  has_many :professionals, :through => :topics, :conditions => {:is_professional => true}
  has_many :questions,     :through => :topics
  has_many :guides,        :through => :topics

  def self.most_popular(n = 10)
    self.order("questions_count DESC").limit(n)
  end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController

  def index
    @categories = Category.all

    @humanized_categories = @categories.map {|category| {:id => category.id, :name => category.name}}

    respond_to do |format|
      format.html
      format.json { render :json => @humanized_categories }
      format.xml  { render :xml => @humanized_categories }
    end
  end

  def show
    @category = Category.find(params[:id])

    @questions = @category.questions.find_all_by_locale(@user_locale)
    @professionals = @category.professionals.uniq

    @topics = @category.topics
    @professions = @category.professions

    respond_to do |format|
      format.html
      format.json { render :json => @category }
      format.xml  { render :xml => @category }
    end
  end

end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/views/categories/show.html.haml
- content_for :title, t("categories.show.page_title", :category => @category.name)

%section#content
  .container
    .row
      .twelve.columns
        %h1
          = @category.name.html_safe
        - unless @category.description.blank?
          %p.description
            = @category.description.html_safe
        %hr
      .eight.columns
        %section#browse-by-taxonomy
          .container
            %h5.topics-title= t("topics.index.title").html_safe
            %ul.topics.block-grid.three-up
              - @category.topics.each do |topic|
                %li.topic= link_to topic.name, category_topic_path(@category, topic), :class => "topic-name", :title => "#{@category.name} / #{topic.name}"
            %h5.professions-title= t("professions.index.title").html_safe
            %ul.professions.block-grid.three-up
              - @category.professions.each do |profession|
                %li.profession= link_to profession.name, category_profession_path(@category, profession), :class => "profession-name", :title => "#{@category.name} / #{profession.name}"
        - unless @professionals.blank?
          %section
            .container
              %h4= t("professionals.count_in_taxonomy", :count => @professionals.count, :taxonomy => @category.name.downcase).html_safe
              - unless @professionals.blank?
                %ul.looper.professionals.block-grid.three-up.mobile-one-up
                  - @professionals.each do |professional|
                    %li= render "professionals/loops/regular", :professional => professional
              - else
                %p.no-records
                  = t("professionals.count.zero").html_safe
      .four.columns
        %section#questions
          .container
            %h4= t("questions.count_in_taxonomy", :count => @questions.count, :taxonomy => @category.name.downcase).html_safe
            - unless @questions.blank?
              %ul.looper.questions
                - @questions.each do |question|
                  %li= render "questions/shared/loop", :question => question
            - else
              %p.no-records
                = t("questions.count.zero").html_safe